services:
  sensor:
    image: baukmeister/sensor-app
    build:
      context: ..
      dockerfile: ./mosquitto_apps/sensor/Dockerfile
  leader:
    image: baukmeister/leader-app
    build:
      context: ..
      dockerfile: ./mosquitto_apps/leader/Dockerfile