services:
  sensor:
    image: baukmeister/mosquitto_apps-sensor
    build:
      context: ..
      dockerfile: ./mosquitto_apps/sensor/Dockerfile
  leader:
    build:
      context: ..
      dockerfile: ./mosquitto_apps/leader/Dockerfile